### PR TITLE
magento graphql-ce#970  Cannot return several errors for one GraphQL request

### LINKED ISSUE #970: Cannot return several errors for one GraphQL request
Now there is no ability to throw two errors, we can only implode it in one string(as in https://github.com/magento/graphql-ce/issues/961 in method getAddressErrors()). 

If you create exception GraphQlInputException it has method `addError()`, so you can add additional errors, but it doesn't work.See screenshot, I added two errors with method `addError()`, but it returns only one.

**Actual result:**
Only one last error is returned.
Screen Shot 2019-09-27 at 13 42 29

**Expected result:**
``` json
{
  "errors": [
    {
      "message": "First error.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    },
    {
      "message": "Second error.",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by lenaorobei**
- fixed magento/graphql-ce#970
- made it possible to use `addError` method of `GraphQlInputException`  in order to show multiple input validation error messages.

Example:
``` php
$e = new GraphQlInputException(__('Address validation error'));
/** @var \Magento\Framework\Phrase $error */
foreach ($errors as $error) {
    $e->addError(new GraphQlInputException(__($error)));
}
throw $e;
```

### CODE REVIEW

**Review by cpartica — APPROVED** [review]
changes look good. It's a needed change

File: lib/internal/Magento/Framework/GraphQl/Exception/GraphQlInputException.php [hunk 1]
```diff
@@ -51,4 +60,22 @@ public function getCategory() : string
     {
         return self::EXCEPTION_CATEGORY;
     }
+
+    /**
+     * @param LocalizedException $exception
+     * @return $this
+     */
+    public function addError(LocalizedException $exception): self
```
Comment (naydav) [inline lib/internal/Magento/Framework/GraphQl/Exception/GraphQlInputException.php:70]: I prefer an immutable type of objects. We can initialization to `construct`. But it's a recommendation but not a requirement.

**Review by cpartica — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-6118](https://jira.corp.magento.com/browse/ENGCOM-6118) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by TomashKhamlai** [comment]
@lenaorobei, could you provide a case where it is possible to test it? I had hopes on #961, but it is fixed now. I just wanted to verify that both `data` and `errors` arrays are present in the response body.
