### PR TITLE
Fixed #176 - Show only active CMS Blocks

### LINKED ISSUE #176: Show only active CMS Blocks
### Preconditions
1. Magento 2.3-develop + sample data (sample data not necessary)
2. Php 7.1
3. MariaDB 10.1.17

### Steps to reproduce
1. Checkout to branch 31-cms-page-graphql-support
Pull request https://github.com/magento/graphql-ce/pull/105
2. Disable some CMS block: MagentoAdmin > Content > Blocks > choose_your_block ->
Enable Block: NO -> Save
3. Run this GraphQL query:
```
{
  cmsBlocks (identifiers: ["disabled_cms_block", "enabled_cms_block"]){
    items{
      title
      identifier
      content
    }
  }
}
```

**disabled_cms_block:** identifier of the disabled cms_block
**enabled_cms_block:** identifier of the enabled cms_block

### Expected result

1. Get only cms_blocks with status: enabled.
```
{
  "data": {
    "cmsBlocks": {
      "items": [
        {
          "title": "Home banner 1"
        }
      ]
    }
  }
}
```

### Actual result

```
{
  "errors": [
    {
      "message": "No such entity.",
      "category": "graphql-no-such-entity",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "cmsBlocks"
      ]
    }
  ],
  "data": {
    "cmsBlocks": null
  }
}
```

**Visualization**

error

**Settings**

settings

**Test**

With GraphQL query for one cms_block it works in a right way!

awesome

awesome2

### PR DESCRIPTION
**Pull request by ronak2ram**
### Description
Removed only active block checking code.

### Fixed Issues (if relevant)
1. magento/graphql-ce#176 : Show only active CMS Blocks

### Steps to reproduce
1. Checkout to branch 31-cms-page-graphql-support
Pull request https://github.com/magento/graphql-ce/pull/105
2. Disable some CMS block: MagentoAdmin > Content > Blocks > choose_your_block ->
Enable Block: NO -> Save
3. Run this GraphQL query:
```
{
  cmsBlocks (identifiers: ["disabled_cms_block", "enabled_cms_block"]){
    items{
      title
      identifier
      content
    }
  }
}
```

**disabled_cms_block:** identifier of the disabled cms_block
**enabled_cms_block:** identifier of the enabled cms_block

### Expected result

1. Get only cms_blocks with status: enabled.
```
{
  "data": {
    "cmsBlocks": {
      "items": [
        {
          "title": "This is a enabled cms block",
          "identifier": "enabled_cms_block",
          "content": "Happy to help you"
        }
      ]
    }
  }
}
```

### Actual result

```
{
  "errors": [
    {
      "message": "No such entity.",
      "category": "graphql-no-such-entity",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "cmsBlocks"
      ]
    }
  ],
  "data": {
    "cmsBlocks": null
  }
}
```

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

File: app/code/Magento/CmsGraphQl/Model/Resolver/Blocks.php [hunk 1]
```diff
@@ -78,7 +78,10 @@ private function getBlocksData(array $blockIdentifiers): array
         $blocksData = [];
         try {
             foreach ($blockIdentifiers as $blockIdentifier) {
-                $blocksData[$blockIdentifier] = $this->blockDataProvider->getData($blockIdentifier);
+                $blockData = $this->blockDataProvider->getData($blockIdentifier);
+                if (!empty($blockData)) {
+                    $blocksData[$blockIdentifier] = $blockData;
+                }
```
Comment (paliarush) [inline app/code/Magento/CmsGraphQl/Model/Resolver/Blocks.php]: We need to log the fact that some of the requested blocks were not found, please add this to the `else`.

**Review by paliarush — APPROVED** [review]
@ronak2ram thank you for making all necessary changes. The PR looks good now.

File: app/code/Magento/CmsGraphQl/Model/Resolver/Blocks.php (hunk 1 above)
Comment (naydav) [reply app/code/Magento/CmsGraphQl/Model/Resolver/Blocks.php]: I provided a little refactoring of this PR
Now blocks data is located in `data` section, and errors are located in `errors` section

Also, I removed the logging, because there it’s way to log overflow logfile if I send non-existent block id
And at the same time for the client, there is no information what is the actual error (error is only on the server)

**Comment by naydav** [comment]
Result:

Request
```
{
  cmsBlocks (identifiers: ["disabled_block", "enabled_block"]){
    items{
      title
      identifier
      content
    }
  }
}
```

Response
```
{
  "errors": [
    {
      "message": "The CMS block with the \"disabled_block\" ID doesn't exist.",
      "category": "graphql-no-such-entity",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "cmsBlocks",
        "items",
        0
      ]
    }
  ],
  "data": {
    "cmsBlocks": {
      "items": [
        null,
        {
          "title": "enabled_block",
          "identifier": "enabled_block",
          "content": "<p>enabled_block enabled_block enabled_block</p>"
        }
      ]
    }
  }
}
```

File: dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQl/ResponseContainsErrorsException.php [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+     */
+    private $responseData;
+
+    /**
+     * @param string $message
+     * @param array $responseData
+     * @param \Exception|null $cause
+     * @param int $code
+     */
+    public function __construct(string $message, array $responseData, \Exception $cause = null, int $code = 0)
```
Comment (paliarush) [inline dev/tests/api-functional/framework/Magento/TestFramework/TestCase/GraphQl/ResponseContainsErrorsException.php:26]: We should not swap the original arguments order to comply with Liskov substitution principle.

**Comment by paliarush** [comment]
Looks like response structure does not match the request structure after the fix (there is additional `data` level). Usually in GraphQL they should match.
